POST http://localhost:8080/todos HTTP/1.1
content-type: application/json

{
    "title": "test title",
    "completed": true
}

###

GET http://localhost:8080/todos HTTP/1.1
content-type: application/json

###


POST http://localhost:8080/todos/60b5cd3b-eaee-42fa-8c8b-9009c6f0fe4f/comment HTTP/1.1
content-type: application/json

{
    "content": "test comment 3"
}
