POST http://localhost:8080/todos HTTP/1.1
content-type: application/json

{
    "title": "test title",
    "completed": true
}

###

GET http://localhost:8080/todos HTTP/1.1
content-type: application/json

###


POST http://localhost:8080/todos/c7419a82-0bec-4c38-98ff-f0499bb2fdd0/comment HTTP/1.1
content-type: application/json

{
    "content": "test comment 3"
}
