POST http://localhost:8080/todos HTTP/1.1
content-type: application/json

{
    "title": "test title",
    "completed": true
}

###

GET http://localhost:8080/todos HTTP/1.1
content-type: application/json

###


POST http://localhost:8080/todos/0ba64fa0-6ed6-48ba-b3bf-b145270a90ed/comment HTTP/1.1
content-type: application/json

{
    "content": "test comment 3"
}

###

POST http://localhost:8080/todos/0ba64fa0-6ed6-48ba-b3bf-b145270a90ed/priority HTTP/1.1
content-type: application/json

{
    "content": "prio1"
}
